#!/usr/bin/env zsh
set -eu
default_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
parallel --no-notice git branch --delete {} ::: $(git branch --merged|rg --invert-match "\\*|${default_branch}")
git fetch --prune
