#!/usr/bin/env bash
set -eu
default_branch=$(git symbolic-ref refs/remotes/origin/HEAD|sed 's@^refs/remotes/origin/@@')
git branch --merged|grep --invert-match -E "\\*|${default_branch}"|xargs git branch --delete
git fetch --prune
