{ pkgs, ... }:
{
  services.locate = {
    enable = true;
    package = pkgs.plocate;
    interval = "hourly";
    pruneNames = [
      "$Recycle.Bin"
      ".Trash"
      ".Trash-1000"
      ".bzr"
      ".cabal"
      ".cache"
      ".cargo"
      ".dub"
      ".gem"
      ".ghcup"
      ".git"
      ".go"
      ".hg"
      ".julia"
      ".metals"
      ".npm"
      ".pyenv"
      ".rbenv"
      ".rustup"
      ".snapshots"
      ".stack"
      ".stack-work"
      ".stack-work-fast"
      ".stack-work-profile"
      ".stack-work-test"
      ".svn"
      "Trash"
      "WinSxS"
      "__pycache__"
      "_cache"
      "_site"
      "appcache"
      "cache"
      "cache2"
      "cached"
      "cdk.out"
      "dist"
      "dist-newstyle"
      "dist-packages"
      "eln-cache"
      "elpy"
      "file-backup"
      "htmlcache"
      "node_modules"
      "projects" # claude code
      "site-packages"
      "steam-runtime"
      "store"
      "target"
      "texmf-dist"
      "undo-tree"
      "virtualenv"
    ];
  };
}
