#!/bin/bash
set -eu
[[ $(git config user.name) == $(git config --global user.name) &&
       $(git config user.email) == $(git config --global user.email) ]] ||
    (echo "gitのユーザー名がグローバルと違います" &&
         exit 1)
