name: Setup Nix
description: Reusable action for nix config

inputs:
  cachix-auth-token:
    description: Cachix authentication token
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: ncaq/nix-composite-action@5a61f70ad5b7d2f276732e14355b7fb2ddd4caaf # v1.3.0
      with:
        cachix-auth-token: "${{ inputs.cachix-auth-token }}"
        # セルフホストランナーのためflake.nixの内容を転写します。
        # flake.nixの内容と乖離しないように注意してください。
        extra-nix-config: >
          substituters =
          https://cache.nixos.org/
          https://niks3-public.ncaq.net/
          https://ncaq.cachix.org/
          https://nix-community.cachix.org/
          https://nix-on-droid.cachix.org/
          https://microvm.cachix.org/

          trusted-public-keys =
          cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          niks3-public.ncaq.net-1:e/B9GomqDchMBmx3IW/TMQDF8sjUCQzEofKhpehXl04=
          ncaq.cachix.org-1:XF346GXI2n77SB5Yzqwhdfo7r0nFcZBaHsiiMOEljiE=
          nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
          nix-on-droid.cachix.org-1:56snoMJTXmDRC1Ei24CmKoUqvHJ9XCp+nidK7qkMQrU=
          microvm.cachix.org-1:oXnBc6hRE3eX5rSYdRyMYXnfzcCxC7yKPTbZXALsqys=
