{ ... }:
{
  programs.fastfetch = {
    enable = true;
    settings = {
      "$schema" = "https://github.com/fastfetch-cli/fastfetch/raw/master/doc/json_schema.json";
      logo = "none";
      modules = [
        "title"
        "os"
        "host"
        "board"
        "kernel"
        "bios"
        "bootmgr"
        "initsystem"
        "lm"
        "shell"
        "display"
        "de"
        "wm"
        "wmtheme"
        "terminal"
        "cpu"
        "cpucache"
        "cpuusage"
        "gpu"
        "disk"
        "diskIO"
        "memory"
        "swap"
        "battery"
        "bluetooth"
        "bluetoothradio"
        "brightness"
        "camera"
        "dns"
        "font"
        "gamepad"
        "keyboard"
        "loadavg"
        "locale"
        "localip"
        "media"
        "mouse"
        "netio"
        "opencl"
        "opengl"
        "vulkan"
        "publicip"
        "sound"
        "terminal"
        "terminalfont"
        "terminalsize"
        "terminaltheme"
        "tpm"
        "uptime"
        "users"
        "wallpaper"
        "weather"
        "wifi"
      ];
    };
  };
}
