{ pkgs, ... }:
{
  # 様々なツールで利用するlspサーバをインストールします。
  # Emacsなどのテキストエディタや、
  # コーディングエージェントなどが利用します。
  home.packages = with pkgs; [
    astro-language-server
    bash-language-server
    biome
    ccls
    clang-tools
    clojure-lsp
    cmake-language-server
    csharp-ls
    dart
    dhall-lsp-server
    docker-compose-language-service
    dockerfile-language-server
    elixir-ls
    elmPackages.elm-language-server
    erlang-language-platform
    fortls
    fsautocomplete
    gleam
    gopls
    graphql-language-service-cli
    haskell-language-server
    jdt-language-server
    kotlin-language-server
    ltex-ls-plus
    lua-language-server
    marksman
    metals
    nginx-language-server
    nil
    nixd
    ocamlPackages.ocaml-lsp
    omnisharp-roslyn
    oxlint
    prisma_7
    pyright
    ruby-lsp
    rust-analyzer
    serve-d
    sourcekit-lsp
    sqls
    svelte-language-server
    tailwindcss-language-server
    taplo
    terraform-ls
    texlab
    tinymist
    ty
    typescript-language-server
    vscode-langservers-extracted
    vue-language-server
    yaml-language-server
    zls
  ];
}
