{
  pkgs,
  config,
  inputs,
  ...
}:
let
  addr = config.machineAddresses.niks3-public;
  user = config.containerUsers.niks3-public;
  niks3User = {
    inherit (user) uid;
    group = "niks3-public";
    isSystemUser = true;
  };
in
{
  containers.niks3-public = {
    autoStart = true;
    ephemeral = true;
    privateNetwork = true;
    privateUsers = "identity";
    hostAddress = addr.host;
    localAddress = addr.guest;
    bindMounts = {
      "/run/postgresql" = {
        hostPath = "/run/postgresql";
        isReadOnly = true;
      };
      "/etc/niks3-public/s3-access-key" = {
        hostPath = "/run/niks3-public/s3-access-key";
        isReadOnly = true;
      };
      "/etc/niks3-public/s3-secret-key" = {
        hostPath = "/run/niks3-public/s3-secret-key";
        isReadOnly = true;
      };
      "/etc/niks3-public/api-token" = {
        hostPath = config.sops.secrets."niks3-public-api-token".path;
        isReadOnly = true;
      };
      "/etc/niks3-public/sign-key" = {
        hostPath = config.sops.secrets."niks3-public-sign-key".path;
        isReadOnly = true;
      };
    };
    config =
      { lib, ... }:
      {
        imports = [ inputs.niks3.nixosModules.niks3 ];
        system.stateVersion = "25.11";
        networking = {
          useHostResolvConf = lib.mkForce false;
          firewall.allowedTCPPorts = [ 5751 ];
          # Cloudflare Tunnel経由だと`Content-Encoding: zstd`が透過的に解凍され、
          # readProxyのnarinfo読み取りが壊れるため、
          # ホスト上のCaddy経由でGarageコンテナに接続する。
          # CaddyがLet's Encrypt証明書(DNS-01)でTLS terminationし、
          # GarageへはHTTPで転送する。
          # presigned URLはhttps://garage.ncaq.net/...のままなので、
          # 外部クライアントはCloudflare Tunnel経由でアクセスできる。
          hosts."${addr.host}" = [ "garage.ncaq.net" ];
        };
        users = {
          users.niks3-public = niks3User;
          groups.niks3-public.gid = user.gid;
        };
        services = {
          resolved.enable = true;
          niks3 = {
            enable = true;
            user = "niks3-public";
            group = "niks3-public";
            httpAddr = "[::]:5751";
            database = {
              createLocally = false;
              connectionString = "postgres:///niks3-public?host=/run/postgresql";
            };
            s3 = {
              endpoint = "garage.ncaq.net";
              bucket = "niks3-public";
              region = "garage";
              useSSL = true;
              accessKeyFile = "/etc/niks3-public/s3-access-key";
              secretKeyFile = "/etc/niks3-public/s3-secret-key";
            };
            apiTokenFile = "/etc/niks3-public/api-token";
            signKeyFiles = [ "/etc/niks3-public/sign-key" ];
            cacheUrl = "https://niks3-public.ncaq.net";
            readProxy.enable = true;
            oidc.providers.github = {
              issuer = "https://token.actions.githubusercontent.com";
              audience = "https://niks3-public.ncaq.net";
              boundClaims = {
                repository_owner = [ "ncaq" ];
              };
            };
          };
        };
      };
  };

  users = {
    users.niks3-public = niks3User;
    groups.niks3-public.gid = user.gid;
  };

  postgresClient = [ "niks3-public" ];

  systemd.services = {
    "container@niks3-public" = {
      requires = [
        "caddy.service"
        "container@postgresql.service"
        "garage-setup-niks3-public.service"
      ];
      after = [
        "caddy.service"
        "container@postgresql.service"
        "garage-setup-niks3-public.service"
      ];
    };
    garage-setup-niks3-public = import ../../../lib/garage-setup.nix {
      inherit pkgs config;
      name = "niks3-public";
    };
  };

  # Managed by sops-nix.
  # S3 keys are dynamically generated by garage-setup-niks3-public on each boot.
  # To create api_token and sign_key (first time only):
  # ```
  # API_TOKEN=$(openssl rand -base64 36)
  # nix key generate-secret --key-name niks3-public.ncaq.net-1 > /tmp/niks3-sign-key
  # ```
  # Then `sops secrets/seminar/niks3-public.yaml` and set:
  # ```
  # api_token: <base64>
  # sign_key: niks3-public.ncaq.net-1:<base64>
  # ```
  # The public key output from `nix key convert-secret-to-public` should be added
  # to nix.conf as `trusted-public-keys` on clients.
  sops.secrets = {
    "niks3-public-api-token" = {
      sopsFile = ../../../secrets/seminar/niks3-public.yaml;
      key = "api_token";
      owner = "niks3-public";
      group = "niks3-public";
      mode = "0400";
    };
    "niks3-public-sign-key" = {
      sopsFile = ../../../secrets/seminar/niks3-public.yaml;
      key = "sign_key";
      owner = "niks3-public";
      group = "niks3-public";
      mode = "0400";
    };
  };
}
