{
  pkgs,
  config,
  inputs,
  ...
}:
let
  addr = config.machineAddresses.niks3-private;
  user = config.containerUsers.niks3-private;
  niks3User = {
    inherit (user) uid;
    group = "niks3-private";
    isSystemUser = true;
  };
in
{
  containers.niks3-private = {
    autoStart = true;
    ephemeral = true;
    privateNetwork = true;
    hostAddress = addr.host;
    localAddress = addr.guest;
    bindMounts = {
      "/run/postgresql" = {
        hostPath = "/run/postgresql";
        isReadOnly = true;
      };
      "/etc/niks3-private/s3-access-key" = {
        hostPath = "/run/niks3-private/s3-access-key";
        isReadOnly = true;
      };
      "/etc/niks3-private/s3-secret-key" = {
        hostPath = "/run/niks3-private/s3-secret-key";
        isReadOnly = true;
      };
      "/etc/niks3-private/api-token" = {
        hostPath = config.sops.secrets."niks3-private-api-token".path;
        isReadOnly = true;
      };
      "/etc/niks3-private/sign-key" = {
        hostPath = config.sops.secrets."niks3-private-sign-key".path;
        isReadOnly = true;
      };
    };
    config =
      { lib, ... }:
      {
        imports = [ inputs.niks3.nixosModules.niks3 ];
        system.stateVersion = "25.11";
        networking = {
          useHostResolvConf = lib.mkForce false;
          firewall.allowedTCPPorts = [ 5751 ];
          # Cloudflare Tunnel経由だと`Content-Encoding: zstd`が透過的に解凍され、
          # readProxyのnarinfo読み取りが壊れるため、
          # ホスト上のCaddy経由でGarageコンテナに接続する。
          # CaddyがLet's Encrypt証明書(DNS-01)でTLS terminationし、
          # GarageへはHTTPで転送する。
          # presigned URLはhttps://garage.ncaq.net/...のままなので、
          # 外部クライアントはCloudflare Tunnel経由でアクセスできる。
          hosts."${addr.host}" = [ "garage.ncaq.net" ];
        };
        users = {
          users.niks3-private = niks3User;
          groups.niks3-private.gid = user.gid;
        };
        services = {
          resolved.enable = true;
          niks3 = {
            enable = true;
            user = "niks3-private";
            group = "niks3-private";
            httpAddr = "[::]:5751";
            database = {
              createLocally = false;
              connectionString = "postgres:///niks3-private?host=/run/postgresql";
            };
            s3 = {
              endpoint = "garage.ncaq.net";
              bucket = "niks3-private";
              region = "garage";
              useSSL = true;
              accessKeyFile = "/etc/niks3-private/s3-access-key";
              secretKeyFile = "/etc/niks3-private/s3-secret-key";
            };
            apiTokenFile = "/etc/niks3-private/api-token";
            signKeyFiles = [ "/etc/niks3-private/sign-key" ];
            # Tailscale Serve経由でHTTPSアクセスされるURL。
            cacheUrl = "https://seminar.border-saurolophus.ts.net:8443/niks3/private/";
            # readはTailscaleネットワーク認証、writeはAPIトークン認証。
            readProxy.enable = true;
          };
        };
      };
  };

  users = {
    users.niks3-private = niks3User;
    groups.niks3-private.gid = user.gid;
  };

  systemd.services = {
    "container@niks3-private" = {
      requires = [
        "caddy.service"
        "garage-setup-niks3-private.service"
        "postgresql.service"
      ];
      after = [
        "caddy.service"
        "garage-setup-niks3-private.service"
        "postgresql.service"
      ];
    };
    garage-setup-niks3-private = import ../../../lib/garage-setup.nix {
      inherit pkgs config;
      name = "niks3-private";
    };
  };

  # Managed by sops-nix.
  # S3 keys are dynamically generated by garage-setup-niks3-private on each boot.
  # To create api_token and sign_key (first time only):
  # ```
  # API_TOKEN=$(openssl rand -base64 36)
  # nix key generate-secret --key-name niks3-private.ncaq.net-1 > /tmp/niks3-sign-key
  # ```
  # Then `sops secrets/niks3-private.yaml` and set:
  # ```
  # api_token: <base64>
  # sign_key: niks3-private.ncaq.net-1:<base64>
  # ```
  # The public key output from `nix key convert-secret-to-public` should be added
  # to nix.conf as `trusted-public-keys` on clients.
  sops.secrets = {
    "niks3-private-api-token" = {
      sopsFile = ../../../secrets/niks3-private.yaml;
      key = "api_token";
      owner = "niks3-private";
      group = "niks3-private";
      mode = "0400";
    };
    "niks3-private-sign-key" = {
      sopsFile = ../../../secrets/niks3-private.yaml;
      key = "sign_key";
      owner = "niks3-private";
      group = "niks3-private";
      mode = "0400";
    };
  };
}
