name: nvd-diff

on:
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nvd-diff:
    name: nvd-diff
    # フォークPRは除外されます。
    if: github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: read # リポジトリコンテンツの読み取り
      id-token: write # `ncaq/nix-composite-action`内のniks3-publicとのOIDC認証に使用
      pull-requests: write # PRコメントのupsert
    runs-on: [self-hosted, Linux]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # base refのworktree展開のために全オブジェクトを要求。
          # 履歴の浅さに依存しない安全側に倒しています。
          # そこまで重いリポジトリでもないのでフルに要求しても問題はありません。
          fetch-depth: 0
          persist-credentials: false
      - uses: ncaq/nix-composite-action@6e28cd44693083d063bed5baf36e912c6807a151 # v1.1.1
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Run nvd-pr-diff
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix run .#nvd-pr-diff
